Payment confirmation scene
kosmo-dev/NFT-Marketplace pull request #26
Opened 2023-09-15 08:33 UTC by kosmo-dev

Выбранная архитектура - MVP
Верстка кодом
Ссылка на таск-трекер https://trello.com/b/Sa1Xo3yu/%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%BD%D1%8B%D0%B9-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82-%EF%A3%BF
файл с декомпозицией
NFT Marketplace/Scenes /Cart/epic_cart_plan.md

Также я добавил в tabBarItem значок количества предметов в корзине. Он обновляется автоматически при изменении количества предметов в корзине. Я считаю, что это улучшит пользовательский опыт.

2023-09-17 04:53 UTC, protos17 requested changes

2023-09-17 04:53 UTC, protos17 commented on NFT Marketplace/Scenes /Payment/PaymentPresenter.swift
>          static let termsOfUseURL = "https://yandex.ru/legal/practicum_termsofuse/"
Вот здесь открываются скобочки у экстеншена и энама, но нет закрывающих, из-за чего проект не запускается

2023-09-17 04:53 UTC, protos17 commented on NFT Marketplace/Scenes /Payment/PaymentViewController.swift
>                  payButton.heightAnchor.constraint(equalToConstant: Constants.buttonHeight)
Constants отсутствуют, ты их переименовал в Const, поэтому необходимо здесь тоже переименовать

2023-09-17 04:53 UTC, protos17 commented on NFT Marketplace/Scenes /Payment/PaymentViewController.swift
> -        let groupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1), heightDimension: .estimated(Constants.cellEstimatedHeight))
На 227 строчке необходимо переименовать в Const чтобы проект запускался

2023-09-17 04:53 UTC, protos17 commented on NFT Marketplace/Scenes /Payment/PaymentViewController.swift
> -                payDescription.topAnchor.constraint(equalTo: payView.topAnchor, constant: Constants.defaultOffset),
Чтобы приложение не вылетало при нажатии на кнопку "К оплате", необходимо добавить loadingIndicator на вьюшку:
[payDescription, userAgreementButton, payButton, loadingIndicator].forEach { payView.addSubview($0) }

2023-09-17 04:53 UTC, protos17 commented on NFT Marketplace/Scenes /Cart/CartPresenter.swift
> +        viewController?.showAlertController(alerts: alerts)
Необходимо добавить еще кнопку закрытия алерта

2023-09-17 04:53 UTC, protos17 commented on NFT Marketplace/Scenes /Cart/CartPresenter.swift
> +                id: nft.id, imageURL: nft.images[0], title: nft.name, price: "\(priceString) ETH", rating: nft.rating)
К первому элементу массива лучше и безопасней обращаться через first:

images.first

или сначала делать проверку, что массив не пустой, а лишь затем обращаться по индексу

2023-09-17 04:53 UTC, protos17 commented on NFT Marketplace/Scenes /Cart/CartPresenter.swift
> +        if paymentFlowStarted && cartController.cart.isEmpty == true {
Сравнения с true можно опускать и просто писать cartController.cart.isEmpty

2023-09-17 04:53 UTC, protos17 commented on NFT Marketplace/Scenes /Payment/PaymentManager.swift
> +    var networkManager: NetworkManagerProtocol
Здесь можно заменить на private let

2023-09-17 04:53 UTC, protos17 commented on NFT Marketplace/Scenes /PaymentConfirmation/PaymentConfirmationViewController.swift
> +            button.heightAnchor.constraint(equalToConstant: 60)
Рекомендую вынести тоже их в константы класса

2023-09-17 08:19 UTC, kosmo-dev commented on NFT Marketplace/Scenes /Payment/PaymentPresenter.swift
>          static let termsOfUseURL = "https://yandex.ru/legal/practicum_termsofuse/"
После мерджа внес все исправления, но забыл сделать коммит 🤦‍♂️

2023-09-18 16:16 UTC, protos17 approved these changes

2023-09-18 16:56 UTC, merged